# Регион для часов
region: "Europe/Moscow"

# Материал для цифр
numMaterial: "BEDROCK"

# Материал для двоеточия
pointMaterial: "BEDROCK"

# Формат времени 24 часовой или 12 часовой
use12HourFormat: false

# Размер часов
# Максимально рекомендуемое значение - 4
size: 1
